steps:
  install:
    image: danlynn/ember-cli:3.28.5
    commands:
      - npm ci
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
when:
  event: tag
  ref: refs/tags/v*