matrix:
  scenario:
    - ember-lts-3.28
steps:
  - name: ${scenario}
    image: danlynn/ember-cli:3.28.5
    commands:
      - npm ci
      - npx ember try:one ${scenario}
when:
  event:
    - pull_request